### ISSUE TITLE
Orchestrator Improvement

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/release#132]
due date: 10/06/2020

# Description

The Gravitee Orchestrator need to monitor the status of each pipeline launched in order to fail, wait or go to the next step

# Tasks detail

* [x] Now, when all pipeline complete their execution with no error, feature is operational, see https://github.com/gravitee-lab/GraviteeCiCdOrchestrator/releases/tag/FINAL_EXEC_STATE_DETECTION : 
 * No Pipeline is triggered, until all the Circle  CI Pipelines have completed with success, in the Current Parallel execution set. 
 * When all the Circle  CI Pipelines have completed with success, in the Current Parallel execution set, this completion is detected, and The `Gravitee CI CD Orchestrator` starts triggering Circle CI Pipelines for the next Parallel Execution Set. 

* [x] To complete this task, a small bug has to be fixed : #143 
* [x] ` - THIS FEATURE IS CANCELLED` To finish this task, only thing left to do, is to test design and implementation of Pipeline execution error detection and handling, using  `src/modules/circleci/status/PipelineExecSetReport.ts`` :  as soon as an error is detected in a Parallel Execution Set (of Pipelines) : no other Parallel Execution Set starts executing, and the whole CI CD Release Process stops, **after** a full execution report is generated and logged, for the currently processed Parallel Execution Set 

* [x] ` - THIS FEATURE IS CANCELLED` Note that I want to add this behavior property : 
 * When a Parallel Execution set has completed with no error, a non-fatal Execution Report also is logged, 
 * to guarantee full accountability through ELK / File Beats later on.

> * manage all logging using winston logging framework => there is a dedicated card for this task

About the ` - THIS FEATURE IS CANCELLED`-labelled features : 
* After working on the subject, I cameto the conclusion that this feature does not make any sense : 
  * building execution report (with or without errors), is the responsibility of a system whatever it is, which gets its data, from the Log management system
  * that kind of system (which builds execution reports) : 
    * is classicaly, in most of the world's systems architectures, designed as a system which is **not** in the software for which execution reports are built. External.
    * with this mindset, we can find **many** execution reporting systems, which will always be and remain, much better at building execution reports, than any component I will develop and maintain, within the `Gravitee CI CD Orchestrator`, will ever be.
    * A classical examples are Kibana and Grafana, and just naming those extremely well known software, is enough to understand it is meaningless, to try and build better reports than those.
  * And this is why the `Gravitee CI CD Orchestrator`, wil from now on have one and only goal, to consolidate accountability of its executions : to have the best logging management, using industry class logging frameworks like `winston`.

**Comment by Jean-Baptiste-Lasselle** [comment]
```bash

a$ npm start -- --help

> GraviteeReleaseOrchestrator@0.0.2 start /home/jibl/gravitee-orchestra
> node ./dist/index.js "--help"


+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x
I am the Gravitee CI CD Orchestrator !
+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x

Options:
      --help        Show help                                          [boolean]
      --version     Show version number                                [boolean]
  -d, --dry-run

                      Use this option to run the CICD Process Stage in 'dry run'
                      mode.                            [boolean] [default: true]
  -s, --cicd-stage  Use this option to specify the CICD Process to run.

                    ['mvn_release'] designed to run in the
                    [https://github.com/gravitee-lab/release] gravitee-lab git
                    repo, will run the maven release process, handling all
                    dependency tree parallelization, with reactive behavior
                    (using RxJS), based on the 'release.json' versioned in the
                    https://github.com/gravitee-lab/release git repository

                    ['pull_req'] designed to run in every the gravitee-lab
                    product component git repo (dev git repos, aka repos where
                    product source code is versioned), to manage pull requests
                    with different Circle CI Pipeline Workflows, for support
                    sprints, dev sprints, or even secops sprints. , and based
                    on git branch names (prefix).

                    ['release_bundle'] designed to run in the [https://github.
                    com/gravitee-lab/docker-library] gravitee-lab git repo, to
                    make bundles (something like tar arhcives, zip files of
                    jars...) used to install many dependencies in Container
                    images.

                    ['oci_release'] designed to run in the [https://github.com
                    /gravitee-lab/docker-library] gravitee-lab git repo, will
                    run the docker release process : docker builds and push
                    all docker images for the product, LTS and STS Releases

                    ['rpm_release'] designed to run in the [https://github.com
                    /gravitee-lab/docker-library] gravitee-lab git repo,
                    [https://github.com/gravitee-lab/rpm-library] gravitee-lab
                    git repo, will run the RPM release process : builds RPM
                    packagesand publishes them to https://packagecloud.io/

                    ['doc_release'] builds and publish the Gravitee
                    Documentation to https://docs.gravitee.io

                    ['social_release'] builds and publish the Social networks
                    , and communication channels announcements (twitter,
                    medium.com, hackernews, facebook, linkedIn, Jumbo posts on
                    website)

                    ['demos_release'] bluegreen deploys all public gravitee
                    demos

         [required] [choices: "mvn_release", "release_bundle", "docker_release",
          "rpm_release", "doc_release", "demos_release", "social_announcements",
                                                                     "pull_req"]
```

**Comment by Jean-Baptiste-Lasselle** [comment]
To test this feature, i need : 
* [ ] To automate git commit and push a `.circleci/config.yml`  Pipeline definition on each Gravitee io dev repo (component) forked in the https://github.com/gravitee-lab Github organization
* [ ] To automate _activating the Circle CI project_ for each Gravitee io dev repo (component) forked in the https://github.com/gravitee-lab Github organization

Note, that I have identified a bug to fix in the Gravitee Ci CD Orchestrator : 
* When required Circle CI projects are not activated on https://app.circleci.com , 
* then the `Gravitee CI CD Orchestrator` does not detect the problem, and should stop its execution(and it does not).
* see issue https://github.com/gravitee-lab/GraviteeCiCdOrchestrator/issues/28

**Comment by Jean-Baptiste-Lasselle** [comment]
* Now, when all pipeline complete their execution with no error, feature is operational, see https://github.com/gravitee-lab/GraviteeCiCdOrchestrator/releases/tag/FINAL_EXEC_STATE_DETECTION

* To finish this task, only thing left to do, is to test design and implementation of Pipeline execution error detection and handling, using  `src/modules/circleci/status/PipelineExecSetReport.ts`` : 
  * as soon as an error is detected in a Parallel Execution Set (of Pipelines) : 
    * no other Parallel Execution Set starts executing, and the whole CI CD Release Process stops, **after** a full execution report is generated and logged, for the currently processed Parallel Execution Set

**Comment by Jean-Baptiste-Lasselle** [comment]
# Error Management / Winston logging

* I write this quick note, to show how error management is fine, and we just miss the winston logging framework now, 
* that Execution Reports have all data for accountability, from logs
* Indeed, have a look at the below error case, where you can clearly see that as soon as a Pipeline execution fails, the `Gravitee CI CD Orchestrator` detects it, and logs : 
* the Circle Pipeline GUID
* The Circle CI Pipeline Workflow GUID , and its explicit human readable name aswell(below, the `release` workflow)

stderr : 

```bash
[{PipelineExecSetStatusWatcher}] - [getIndexInProgresMatrixOfPipeline] - Pipeline of GUID [de4ab2bc-39ac-4066-ae77-4699c96d9227] was found in progressMatrix, its index is : [1]
DEBUG [{PipelineExecSetStatusWatcher}] - [handleInspectPipelineExecStateResponseData] [occuredProblem = null]
DEBUG [{PipelineExecSetStatusWatcher}] - [handleInspectPipelineExecStateResponseData] - In FOR LOOP Inspecting object [ this.progressMatrix[1] ] : 
----
{
 "pipeline_exec_number": "94",
 "id": "de4ab2bc-39ac-4066-ae77-4699c96d9227",
 "created_at": "2020-10-21T22:16:09.116Z",
 "exec_state": "pending",
 "project_slug": "gh/gravitee-lab/gravitee-fetcher-api",
 "watch_round": 9,
 "workflows_exec_state": [
  {
   "pipeline_id": "de4ab2bc-39ac-4066-ae77-4699c96d9227",
   "id": "ffda01a4-0f3d-40da-9261-c7fff93f258b",
   "name": "release",
   "project_slug": "gh/gravitee-lab/gravitee-fetcher-api",
   "status": "failing",
   "started_by": "a159e94e-3763-474d-8c51-d1ea6ed602d4",
   "pipeline_number": 94,
   "created_at": "2020-10-21T22:16:09Z",
   "stopped_at": "2020-10-21T22:17:28Z"
  }
 ]
}
----
DEBUG [{PipelineExecSetStatusWatcher}] - [handleInspectPipelineExecStateResponseData] [occuredProblem = Error: For Circle CI Pipline of GUID [de4ab2bc-39ac-4066-ae77-4699c96d9227], the [release] workflow of GUID [ffda01a4-0f3d-40da-9261-c7fff93f258b]  at least one job already failed, although not all job have completed their execution] inside wfstate loop
DEBUG [{PipelineExecSetStatusWatcher}] - [handleInspectPipelineExecStateResponseData] - inside if where [PipelineExecSetReportLogger] is instantitated, passing to constructor the Error : [occuredProblem = Error: For Circle CI Pipline of GUID [de4ab2bc-39ac-4066-ae77-4699c96d9227], the [release] workflow of GUID [ffda01a4-0f3d-40da-9261-c7fff93f258b]  at least one job already failed, although not all job have completed their execution] 
/graviteeio/cicd/node_modules/rxjs/internal/util/hostReportError.js:4
    setTimeout(function () { throw err; }, 0);
                             ^

Error: For Circle CI Pipline of GUID [de4ab2bc-39ac-4066-ae77-4699c96d9227], the [release] workflow of GUID [ffda01a4-0f3d-40da-9261-c7fff93f258b]  at least one job already failed, although not all job have completed their execution
    at PipelineExecSetStatusWatcher.handleInspectPipelineExecStateResponseData (/graviteeio/cicd/dist/modules/circleci/status/PipelineExecSetStatusWatcher.js:362:34)
    at SafeSubscriber.__tryOrUnsub (/graviteeio/cicd/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/graviteeio/cicd/node_modules/rxjs/internal/Subscriber.js:143:22)
    at Subscriber._next (/graviteeio/cicd/node_modules/rxjs/internal/Subscriber.js:89:26)
    at Subscriber.next (/graviteeio/cicd/node_modules/rxjs/internal/Subscriber.js:66:18)
    at /graviteeio/cicd/dist/modules/circleci/CircleCIClient.js:254:26
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! GraviteeReleaseOrchestrator@0.0.3 start: `node ./dist/index.js "-s" "mvn_release" "--dry-run"`
npm ERR! Exit status 1
```

**Comment by Jean-Baptiste-Lasselle** [comment]
All bullet points of the TODO list for this task have been completed
